/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    Cocoa: typeof import('./src/components/Cocoa.vue')['default']
    CocoaProducts: typeof import('./src/components/CocoaProducts.vue')['default']
    Cofee: typeof import('./src/components/Cofee.vue')['default']
    CoffeeProducts: typeof import('./src/components/CoffeeProducts.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HomeProductsCacao: typeof import('./src/components/HomeProductsCacao.vue')['default']
    HomeProductsCoffee: typeof import('./src/components/HomeProductsCoffee.vue')['default']
    LogosSection: typeof import('./src/components/LogosSection.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Origenes: typeof import('./src/components/Origenes.vue')['default']
    Origins: typeof import('./src/components/Origins.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Whatwedo: typeof import('./src/components/Whatwedo.vue')['default']
  }
}
