/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    Carrousel: typeof import('./src/components/Carrousel.vue')['default']
    copy: typeof import('./src/components/HomeProductsCoffee copy.vue')['default']
    HomeProducts: typeof import('./src/components/HomeProducts.vue')['default']
    HomeProductsCacao: typeof import('./src/components/HomeProductsCacao.vue')['default']
    HomeProductsCoffee: typeof import('./src/components/HomeProductsCoffee.vue')['default']
    LogosSection: typeof import('./src/components/LogosSection.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
