name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # O la rama que prefieras para el despliegue

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HOSTINGER_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa  # Corrige saltos de línea potenciales
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 157.173.209.163 >> ~/.ssh/known_hosts

      - name: Deploy to Hostinger
        run: |
          rsync -avz --delete -e "ssh -p 65002" ./ u776860763@157.173.209.163:public_html
