name: Deploy to Hostinger

on:
  push:
    branches:
      - master  # Cambia 'main' si tu rama principal tiene otro nombre

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.HOSTINGER_SSH_KEY }}
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 157.173.209.163 >> ~/.ssh/known_hosts

    - name: Deploy to Hostinger
      run: |
        rsync -avz --delete -e "ssh -p 65002 -o StrictHostKeyChecking=no" ./ u776860763@157.173.209.163:public_html
